#!/bin/sh
yiiver=1.1.15
yiihash=022a51
yiifile=yii-$yiiver.$yiihash.tar.gz
yiidir=yii-$yiiver.$yiihash
yiiurl=https://github.com/yiisoft/yii/releases/download/$yiiver/$yiifile

rm -rfv framework

curl -OL $yiiurl
tar -xvzf $yiifile

mv -v $yiidir/framework framework
rm -rfv $yiidir $yiifile