#!/bin/sh
yiiver=1.1.15
yiihash=022a51
yiifile=yii-$yiiver.$yiihash.tar.gz
yiidir=yii-$yiiver.$yiihash
yiiurl=https://github.com/yiisoft/yii/releases/download/$yiiver/$yiifile

repodir="$OPENSHIFT_REPO_DIR"
tmpdir="$OPENSHIFT_TMP_DIR"

echo 'Removing old framework...'
rm -rf framework

echo 'Downloading new framework...'
curl -L $yiiurl >"$tmpdir/$yiifile"

echo 'Extracting framework...'
tar -xzf "$tmpdir/$yiifile" -C "$tmpdir"
mv "$tmpdir/$yiidir/framework" "$repodir/framework"

echo 'Removing temporary files...'
rm -rf "$tmpdir/$yiidir" "$tmpdir/$yiifile"

echo 'Creating necessary directories...'
mkdir -p "$repodir/protected/runtime"
mkdir -p "$repodir/assets"