#!/bin/sh
yiiver=1.1.15
yiihash=022a51
yiifile=yii-$yiiver.$yiihash.tar.gz
yiidir=yii-$yiiver.$yiihash
yiiurl=https://github.com/yiisoft/yii/releases/download/$yiiver/$yiifile

repodir="$OPENSHIFT_REPO_DIR"
tmpdir="$OPENSHIFT_TMP_DIR"

rm -rfv framework

curl -L $yiiurl >"$tmpdir/$yiifile"
tar -xvzf "$tmpdir/$yiifile" -C "$tmpdir"

mv -v "$tmpdir/$yiidir/framework" "$repodir/framework"
rm -rfv "$tmpdir/$yiidir" "$tmpdir/$yiifile"